package emu.grasscutter.game.dungeons.challenge.enums;

public enum ChallengeCondType {
    CHALLENGE_COND_NONE,
    CHALLENGE_COND_IN_TIME,
    CHALLENGE_COND_ALL_TIME,
    CHALLENGE_COND_KILL_COUNT,
    CHALLENGE_COND_SURVIVE,
    CHALLENGE_COND_TIME_INC,
    CHALLENGE_COND_KILL_FAST,
    CHALLENGE_COND_DOWN_LESS,
    CHALLENGE_COND_BEATEN_LESS,
    CHALLENGE_COND_UNNATURAL_COUNT,
    CHALLENGE_COND_FROZEN_LESS,
    CHALLENGE_COND_KILL_MONSTER,
    CHALLENGE_COND_TRIGGER,
    CHALLENGE_COND_GUARD_HP,
    CHALLENGE_COND_TIME_DEC,
}
